README.md

Add note about Linux system dependencies

---

preview/templates/business/components/Main.jsx
preview/templates/minimal/components/Main.jsx

Fix  VAT & Discount prefix position

---

libs/dragNdrop.js
static/css/general.css

Fix Linux,Windows Draggable Window

---

app/components/form/ItemRow.jsx
app/components/form/__tests__/__snapshots__/ItemRow.spec.jsx.snap

values can be float

---

app.js
app/components/invoices/Invoice.jsx
app/components/invoices/__tests__/Invoice.spec.js
app/components/settings/Invoice.jsx
app/containers/Invoices.jsx
app/reducers/SettingsReducer.jsx
app/reducers/__tests__/SettingsReducer.spec.js
preview/components/main/Invoice.jsx
preview/containers/MainContent.jsx
preview/reducers/index.jsx
preview/templates/business/components/Header.jsx
preview/templates/business/components/Logo.jsx
preview/templates/business/index.jsx
preview/templates/minimal/components/Footer.jsx
preview/templates/minimal/components/Header.jsx
preview/templates/minimal/index.jsx

Thanks to @dawsbot for the initial work 👍

Date format

---

app/components/settings/Invoice.jsx
libs/sounds.js
main/save-pdf.js

Fixed error couldn't save as PDF due to changes in #109

Fixed Save As PDF Error

---

app/components/shared/Message.jsx
app/helpers/__mocks__/invoice.js
app/helpers/__tests__/invoice.spec.js
app/helpers/invoice.js
app/middlewares/InvoicesMW.jsx
app/middlewares/__tests__/InvoicesMW.spec.js
preview/templates/business/components/Header.jsx
preview/templates/business/components/Main.jsx
preview/templates/minimal/components/Main.jsx

Various fixes

---

app/components/form/Note.jsx

Add handle reset form to Note component

---

app.js

ref: https://github.com/electron/electron/issues/4322

Linux Gpu Bug

---

app.js

Can you review this, @dawsbot ? 
Thanks!
Fix #117

Refactored setInitialValues()

---

app.js

Skip migration if this is the first time install

Handle settings migration

---

webpack.config.js

https://github.com/webpack/webpack/issues/5931

Temporary fix for webpack #5931

---

app/renderers/menu.js

Make Quit & Check for Update menu available on Windows/Linux as well
Fix https://github.com/hql287/Manta/issues/156

Make Quit & Check for Update menu available on Windows/Linux 

---

app/renderers/menu.js

Show menu items such as Quit, Check for Update based on OS

Refactored app menu

---

app/components/settings/_partials/invoice/Other.jsx

#211 As in the future the german language will be integrated, would it make sense to have the german date notation.

Added german date notation

---

preview/templates/minimal/components/Header.jsx

Added a better Simplified Chinese serif typeface fallback for 'minimal' theme.

Updated template with Chinese typeface fallback

---

app/components/settings/_partials/invoice/Other.jsx

Fixed notification overlay bug

---

README.md

Update screenshots of Manta to show the UI of the current version (v1.1.3).
Fix #241

Updated Screenshots section of ReadMe

---

app/helpers/pouchDB.js
preview/components/shared/index.js
preview/components/sidebar/AccentColor.jsx
preview/components/sidebar/Toggler.jsx
preview/containers/MainContent.jsx
preview/containers/SideBar.jsx
preview/reducers/index.jsx
preview/templates/business/components/Footer.jsx
preview/templates/business/components/Header.jsx
preview/templates/business/components/Main.jsx
preview/templates/minimal/components/Header.jsx

Refactor Accent Colour Component

---

app/actions/__tests__/invoices.spec.js
app/actions/invoices.jsx
app/components/invoices/Invoice.jsx
app/components/invoices/__tests__/Invoice.spec.js
app/components/invoices/__tests__/__snapshots__/Invoice.spec.js.snap
app/constants/actions.jsx
app/containers/Invoices.jsx
app/middlewares/InvoicesMW.jsx
app/middlewares/__tests__/InvoicesMW.spec.js

This feature allows users to quickly clone an invoice.  
Issue #263 
If you need to create exactly the same invoice for two clients, this should be much faster and less error-prone than recreating the invoice from scratch. 
Unit tests have been added to ensure this feature works as expected.

Allow user to duplicate an invoice.

---

README.md

Updated Screenshoots URLs
